[package]
name = "stews"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
clap-verbosity-flag = "2.1.1"
env_logger = "0.10.1"
log = "0.4.20"
pcre = "0.2.3"
